### ISSUE TITLE
what if logic in intercept() throws an exception?

### ISSUE THREAD

**Issue by macarthor** [ChuckerTeam/chucker#113]
it's actually a question than a bug.

intercept() method does not have try/catch for logics other than network request itself.

if your logic throws some exception, the network request/response would fail to be passed to their downstream operators.

am i understanding correctly?

**Comment by cortinico** [comment]
Hey @macarthor 
Thanks for your question and apologize for the late reply but I missed this mail.

> if your logic throws some exception, the network request/response would fail to be passed to their downstream operators.

If our logic throws an `IOException` the behavior is what you wrote. The chain of interceptors will be broken and the network request could fail to fire (based on where the exception is raised).

If our logic throws a different exception, the app will just crash (obviously this will happen only on your debug build). This behavior is intended as this will allow to easily investigate what's the problem rather than having to look through the log to search for a stacktrace.
