### ISSUE TITLE
With notifications disabled, Chucker will still ask for notification permission when launching the activity

### ISSUE THREAD

**Issue by joakimtall** [ChuckerTeam/chucker#1164]
After adding Chucker like this

```
val chuckerInterceptor = ChuckerInterceptor.Builder(context)
    .collector(ChuckerCollector(context, showNotification = false))
    .build()
OkHttpClient.Builder()
    .addInterceptor(chuckerInterceptor)
    ...
```

And then launching it by

```
context.startActivity(Chucker.getLaunchIntent(context))
```

Chucker will then ask for notification permission, and then send no notifications

**Comment by joakimtall** [comment]
I could probably make a PR for this if I got pointers on how to implement it

**Comment by cortinico** [comment]
Yup so the problem is here:
https://github.com/ChuckerTeam/chucker/blob/74b2a857567b92ba7e2f59e136f3dbcce38f5765/library/src/main/kotlin/com/chuckerteam/chucker/internal/ui/MainActivity.kt#L99-L131

We'll have to check from the `ChuckerCollector` if `showNotification == true` before requesting permission

**Comment by joakimtall** [comment]
How can we get a reference to the ChuckerCollector instance? If you want me to take a stab at it

**Comment by cortinico** [comment]
I guess we'll have to create a new field inside the `Chucker` object to store this information

**Comment by joakimtall** [comment]
I have made a PR according to this idea
