### ISSUE TITLE
Is there a way to theme chucker log activity?

### ISSUE THREAD

**Issue by alorma** [ChuckerTeam/chucker#280]
## :warning: Is your feature request related to a problem? Please describe
I'm going to add chucker on our project, and I want to know if there's any way to add a custom theme to chucker so it looks more integrated into the app?

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by vbuberen** [comment]
Hi. No, there is no way to do this.
Also, there were no plans on introducing such feature.
I don't feel that it should appear in Chucker, since it is just a redundant code and it is not cool to add code, which will be useless for the majority of library users.
Feel free to create your fork and customize it as you want.

**Comment by cortinico** [comment]
> Hi. No, there is no way to do this.

To clarify, there is No official supported way (and we're not planning to support this in the future).

Although, you can easily customize the Chucker appearance in your host app. You just need to provide a `<style name="Chucker.BaseTheme">` in your styles and override the colors you want to change:

https://github.com/ChuckerTeam/chucker/blob/73ddd2a7b72dd24e2c13013d10e9c6f8591789a1/library/src/main/res/values/styles.xml#L4-L16

The them you specify in your app will have a higher priority than the one bundled in the library.

As previously mentioned, we don't support this customization. So you can expect this to break even between patch versions.
