### ISSUE TITLE
Consider publishing both main and no-op libs together in one multi-variant way

### ISSUE THREAD

**Issue by autonomousapps** [ChuckerTeam/chucker#362]
## :warning: Is your feature request related to a problem? Please describe
The problem is that adding this library to a project is more verbose than maybe it has to be, and can be error-prone (such as a copy-paste error with debug vs release implementation).

## :bulb: Describe the solution you'd like
I notice you already use maven-publish (or a wrapper around it), and software components for publishing. You may not be aware that there is an `all` component that bundles together all variants into a single variant-aware publication. I honestly am not sure it will work in your use-case, but I think it might. The idea is to get rid of the no-op library and instead put it into a `release` folder in your source tree. And then the "real" lib would go into a `debug` folder. Publish with `components.all` and then users could add just one line of code to their build scripts and gradle would select the right variant at build time.

## :page_facing_up: Additional context
I have a [plugin](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/issues/194) that does some dependency analysis, and it falls over a bit in the presence of libraries using this pattern. I intend to work on a solution at the level of my plugin, but it got me thinking that you could improve your publishing process and make life easier on users.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No
- [x] Maybe

**Comment by autonomousapps** [comment]
I am willing to submit a PR for this, but I don't necessary "want" to :) It doesn't matter to me who does this.

**Comment by vbuberen** [comment]
Thanks for your suggestion.

It is interesting, but for me it seems as losing some flexibility by being able to specify the variant users need for their purpose (if somebody wants to run full library in a release build to test something, for example).

And I am not sure if copying just 2 lines is really error-prone, because there is no need to look for each line in different places or something like that.

**Comment by autonomousapps** [comment]
I should have mentioned this in the original description, but the "error-prone" nature goes a bit farther.

At my work, we publish several android libraries as well as android apps. The libraries are used internally and externally. I added Chucker to one of the libraries (our "api" library) and also added it to an app that used the library. This resulted in very frustrating build failures because we were using the release version of the library (and therefore the release version of chucker) alongside the debug version in the app. The build failed due to duplicate classes. For a while we worked around it by depending on a snapshot of the lib for debug builds, but eventually our resolution was to publish our libraries with `components.all`, so that app consumers would automatically select the right variant.

So I do think it's a real problem. For a long time I was regretting adding this library to my projects, despite its huge utility :P

FWIW, I think you could maintain your flexibility by having two publications, an `all` and a `release` at different coordinates. Maybe the `all` version could be published at `"com.github.ChuckerTeam.Chucker:library-all"`.

**Comment by vbuberen** [comment]
Thanks for clarifications. 

I would like to get an input from @cortinico as well, since I am not optimistic about this particular case.

**Comment by cortinico** [comment]
Hi @autonomousapps 
Thanks for raising this point.

> At my work, we publish several android libraries as well as android apps. The libraries are used internally and externally. I added Chucker to one of the libraries (our "api" library) and also added it to an app that used the library. This resulted in very frustrating build failures because we were using the release version of the library (and therefore the release version of chucker) alongside the debug version in the app. The build failed due to duplicate classes

This seems to me like a misconfiguration of your build. It would be great if you could provide a sample project with an empty app and a library that is using the release version of Chucker and that is failing with duplicate classes. 

On Android the `debug` and the `release` build types are compiled separately so the two dependencies should not clash as in your described scenario.

That being said, offering a variant-aware `library-all` is doable (alongside the `library` and `library-no-op`), but I'm afraid this will introduce more confusion than benefit. 

The current setup is really explicit. Having a single dependency would delegate the artifact selection to the Gradle variant matching mechanism. I'm afraid users will be confused by this as it's not broadly used. On the other hand, having 2 artifacts is a more common pattern, used by other libraries in the Android ecosystem.

**Comment by autonomousapps** [comment]
Thanks for the response.

I don't know why you think this would be a misconfiguration in my build. Given a library L that is published with the release variant (so, library-no-op) and an app A that I'm building with a the debug variant (so, library) (and which relies on the _binary_ L), what would you expect to happen when AGP attempts to build the APK? Both library and library-no-op provide (some of) the same classes. L's metadata (both maven pom and gradle module metadata) indicate it requires library-no-op. Since A relies on library, there _has_ to be a conflict.

(As an aside, I ran japi-cmp over the two versions of this library and they have different ABIs. I think this is a problem. Since they're supposed to be "the same thing" from the build perspective, I think they really ought to have the same ABI.)

I am also not in favor of a library-all publication. I only brought it up because it was suggested that some people might want to use the library publication in a release situation (which is a use-case I don't really get, tbh).

Finally, your comment about having users depend on the gradle variant-matching mechanism misses an important point, which is that they already do. Almost all android devs use gradle to build, and gradle does this by default and with no ability to opt-out.

As a final word, consider that LeakCanary used to follow this pattern, but after a lot of discussion all centered on the problems it caused, finally moved over to using a single-publication pattern. Just because something is a common pattern doesn't make it good.

**Comment by cortinico** [comment]
Thanks for your feedback @autonomousapps 

> I don't know why you think this would be a misconfiguration in my build. Given a library L that is published with the release variant (so, library-no-op) and an app A that I'm building with a the debug variant (so, library) (and which relies on the _binary_ L), what would you expect to happen when AGP attempts to build the APK?

I'm sorry but I can't fully understand your setup. Specifically:

> and an app A that I'm building with a the debug variant (so, library) (and which relies on the _binary_ L)

Both `library` and `library-no-op` are published with a release variant.

In order to help everyone understand the scenario, I've created an example of the setup you describe in my local fork: https://github.com/cortinico/chucker/tree/issue-362-sample (specifically this commit https://github.com/cortinico/chucker/commit/fabfec7071e2f5ac576af45f1a7c4e71c6c811a4)

Here the `app` module is relying:
- Directly on `library-no-op` via `debugImplementation`
- On the `api` module which provides both `library` and `library-no-op`.

This is shaped around your previous comment:

> I added Chucker to one of the libraries (our "api" library) and also added it to an app that used the library. This resulted in very frustrating build failures because we were using the release version of the library (and therefore the release version of chucker) alongside the debug version in the app

I was able to properly build the app both in the `release` and in the `debug` variant. Can I ask you to adapt it to replicate your build failure or your setup?

> (As an aside, I ran japi-cmp over the two versions of this library and they have different ABIs. I think this is a problem. Since they're supposed to be "the same thing" from the build perspective, I think they really ought to have the same ABI.)

This is known, it was already discussed here https://github.com/ChuckerTeam/chucker/issues/357#issuecomment-634328767
The two artifacts are not binary compatible each other. If this is creating problem for your setup, please open another issue and let's discuss it further. Here let's focus on the variant-aware publishing.

> some people might want to use the library publication in a release situation (which is a use-case I don't really get, tbh).

Say you're publishing a developer tool (an App that showcase how to access your public API) to play store, and you want Chucker to be added there. We don't want to restrict this. Or say you have 3 build types: `release`, `debug` and `staging` and you want chucker on `debug` and `staging` only (for your Q&A team).

> As a final word, consider that LeakCanary used to follow this pattern, but after a lot of discussion all centered on the problems it caused, 

I'm happy to discuss this, I would just love to clearly understand what's the problem we're trying to solve so that also others can contribute on the discussion as well.

On this front, it's probably also useful to chat on the [#chucker](https://kotlinlang.slack.com/archives/CRWD6370R) slack channel.

Finally, I don't think that we can really relate to the LeakCanary scenario honestly. LeakCanary has literally no code to setup. Our case is different in a way that we want to allow users to `.addInterceptor(ChuckerInterceptor(context))` and based on the build type this will result in having Chucker active or having an empty interceptor. That's the reason behind offering the `-no-op` artifact.

If the `-no-op` artifact is creating problem to your build, you're not forced to use it, it's just a convenience artifact. You will have to manually make sure you include Chucker only on your debug build (e.g. using source sets). I have an example of this setup in this branch https://github.com/cortinico/chucker/tree/single-artifact-sample (specifically https://github.com/cortinico/chucker/commit/6eca057f4a1eaf4afe36784bc4a83f9297246a08)

**Comment by koral--** [comment]
If I understand correctly proposed approach may cause new kind of issues.

Let's consider the following scenario:
* There is a multi-module and multi-variant app. 
* Some of dependencies have only one configuration: `release` since there is no difference between release and debug.
** So some variants use `setMatchingFallbacks("release")`

With such setup those variants will pick release version of chucker which may be the opposite of the desired effect.

**Comment by MiSikora** [comment]
I wouldn't want to have `one bundle to rule them all` based on a built types and flavours. It shouldn't be assumed how the library is applied. Maybe someone has a need for having Chucker in release builds as it is used for some sort of monitoring tool or whatever the reason is.

Also, I'm not sure if I get it correctly, but I'm also afraid of issues mentioned by @koral-- .

If anything I would be in favour of not having `no-op` flavour at all. It should be up to the consumer side to decide whether they want to apply library or not. I mean, having it is not a big deal as I don't have to apply it anyway, but just saying. :)

**Comment by vbuberen** [comment]
Closing this, since currently we don't plan suggested changes.
