### ISSUE TITLE
ChuckInterceptor without Context, is it possible?

### ISSUE THREAD

**Issue by mochadwi** [ChuckerTeam/chucker#365]
## :warning: Is your feature request related to a problem? Please describe
Our team trying to implement a clean modular architecture that consist 3 modules: `:domain`, `:data` & `:presentation`

`:domain` & `:data` is pure `apply plugin: kotlin` module (no android framework)

## :bulb: Describe the solution you'd like
Currently, Chucker needs `Context` inside RetrofitBuilder, thus we cannot find a workaround for this inside `:data`.

Does chuck possible to use without additional context, like this for example: https://github.com/pandulapeter/beagle/blob/master/beagle-example/src/main/java/com/pandulapeter/beagleExample/networking/NetworkingManager.kt

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by vbuberen** [comment]
Hi @mochadwi 

No, there is no way to use `ChuckerInterceptor` without context. 
But it doesn't mean you can't use Chucker in your project. 

I worked on a project which had pretty much the same architecture as I understand from your message. It had the following structure:
![Structure](https://user-images.githubusercontent.com/13467769/84881779-02198a80-b097-11ea-9435-fe975f537b79.png)

As you might see `remote` is also not an Android module.

Since we used dependency injection (it was Koin) we declared `remote` module (Koin module) in `app` (Gradle module) where we declared things needed for `remote` (Gradle module).
So in `app` (Gradle module) we had file `RemoteModule` like this (renamed some items due to privacy reasons):
<img width="413" alt="Screenshot 2020-06-17 at 12 43 37" src="https://user-images.githubusercontent.com/13467769/84882684-4a857800-b098-11ea-8af4-e16bf17e4e99.png">

As you see we declare `ChuckerInterceptor` in `app`, so we have access to `Context` object and provide it this way.

In our `remote` (Gradle module) we had the following declaration for `AppApiFactory`:
<img width="300" alt="Screenshot 2020-06-17 at 12 46 13" src="https://user-images.githubusercontent.com/13467769/84882937-9f28f300-b098-11ea-9699-8d77f355ea06.png">

As you might see we upcasted `ChuckerInterceptor` to `Interceptor`, so `remote` (Gradle module) has no Chucker in its dependencies.

Hope it helps with your project.

**Comment by mochadwi** [comment]
I see that's solves our problems. By defining `interceptor` as param/constructor like yours.  thanks @vbuberen
