### ISSUE TITLE
Fast Scroll Feature on Response page to have ability to scroll to down 

### ISSUE THREAD

**Issue by nasrabadiAM** [ChuckerTeam/chucker#388]
## :warning:
 The problem is scrolling down inside response page with a long response there, is annoying and difficult.

## :bulb: 
I'd like to add fast scroll feature to that page scrollView.

## :page_facing_up: Additional context
[sample](https://i0.wp.com/androidkt.com////wp-content/uploads/2017/09/Fast-Scrolling.gif?resize=332%2C598&ssl=1)

## :raising_hand: Do you want to develop this feature yourself?
- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
Thanks for reporting this feature request @nasrabadiAM 

> The problem is scrolling down inside response page with a long response there is annoying and difficult.

Can you be a bit more specific? IIRC @vbuberen was working on a feature to "navigate" through the body using the search feature (with two arrows as you do when you search for a string in the browser).

**Comment by nasrabadiAM** [comment]
Sometimes we need to scroll to the end of the response to see what is there, so I Think the search feature is a bit different from this. Actually Scrolling is not suitable for long responses. @cortinico 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31126059/87339862-793e2380-c55c-11ea-9b47-0691bea00218.gif)

**Comment by vbuberen** [comment]
Thanks for suggestion. Yeah, it would be a cool addition. 
There is nothing that will interfere with my work on search in RecyclerView according to info I checked on fast scroll.
However, be careful as there are some issues with it https://issuetracker.google.com/issues/64729576

**Comment by vbuberen** [comment]
Did some additional research on this feature - it seems that the issue I attached in the previous message is ignored by Google for a long time and the only way to have this feature work fine is to either use 3rd party additional library or do some manual fix for RecyclerView.

I would like to avoid additional 3rd party libraries. As to manual fix - I am looking forward for RecyclerView 1.2.0, so would like to wait its stable release and do fix then. 

Due to this I would like to postpone this feature a little bit.
