### ISSUE TITLE
Decouple Chucker from Android

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#393]
## :warning: Is your feature request related to a problem? Please describe

I don't like that `ChuckerInterceptor` is coupled with the Android framework. It restricts it and makes testing harder. The need for doing that in tests makes me sad.

https://github.com/ChuckerTeam/chucker/blob/d919874d602733da1c90ceea1a658d69ea242036/library/src/test/java/com/chuckerteam/chucker/ChuckerInterceptorDelegate.kt#L26-L33

## :bulb: Describe the solution you'd like

Right now this is a primary constructor.

https://github.com/ChuckerTeam/chucker/blob/d919874d602733da1c90ceea1a658d69ea242036/library/src/main/java/com/chuckerteam/chucker/api/ChuckerInterceptor.kt#L39-L45

I'd like to change it and introduce some internal interfaces for i.e. providing resource strings or collecting requests/responses. These interfaces would have implementations based on `Context` that would be used from a secondary constructor that accepts an instance of `Context`.

## :bar_chart: Describe alternatives you've considered

It does not solve the whole problem but some testing issues could be solved by running instrumented tests. I don't think it should be done as the only step and I'd like to make the main proposal happen. However, it would be also good to run instrumented tests with the real scenario setup (I can create a separate issue for this).

## :page_facing_up: Additional context

This is for Chucker `4.x`.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by koral--** [comment]
From what I can see at a first glance (I haven't analyzed Chucker's internals so I may be wrong), the context is needed to initialize some repository (I guess connected with some database) and manage status bar notifications.
So another approach (at least in theory) is to remove context from constructor and take it from the ContentProvider or an AndroidX Startup Initializer. 
Until Chucker is implicitly initialized such way interactions with database may be ignored (using the least path of resistance).

**Comment by MiSikora** [comment]
I'm not sure that this would solve the issue mentioned here. Interceptor still would require these dependencies. So even if they are initialized externally they need to be passed to the interceptor, which would require some sort of a service locator or a singleton.

However, this could remove a need to pass `Context` to a secondary constructor. This would also remove a need to always defensively initialize repositories and so on. To be honest I'm not sure about this. I'm leaning against it because it might give an illusion that Chucker can be used without `Context`.

Unless it would be truly separated from the `Context` and there would be i.e. a separate Android artifact. This is a much bigger change and would require to put more thought into the public API (`HttpTransaction` and so on). Might be something for `4.x` since, from what I understand, there is a desire to redesign API but probably as a separate long term goal.

**Comment by vbuberen** [comment]
I sort of like and dislike the idea. 

It would be awesome to get rid of `Context` when adding `ChuckerInterceptor` in app code, but there are reasons to have it, like repositories initialization or notifications.

The reason I dislike the idea is because the motivation you provided feels like this change is just for testing purposes. So it seems like tests for the sake of tests. While I don't want to underestimate the importance of tests, but I also wouldn't like to make tests more important than the library itself.

As to redesign in 4.x - as of today my idea of redesign is more about changing entities according to #259 and redesign the UI, not the API.

**Comment by MiSikora** [comment]
Well, yes. My main motivation are tests. However, not for tests sake but for making the code more testable. Having interfaces would enable to test real implementations against fake ones and using these in tests of `ChuckerInterceptor`. If in your opinion it does not bring much value I don't have any real need to pursue this.

**Comment by cortinico** [comment]
> Having interfaces would enable to test fake implementations against real ones and using former in tests of `ChuckerInterceptor`. If in your opinion it does not bring much value I don't have any real need to pursue this. :)

I think we should really work in this direction. 

Imho the title of this issue is a bit misleading as "Decouple Chucker from Android" is really out of the scope of this library (we provide a debugging tool for Android, so we need to depend on the framework).

From my point of view we should evolve our API (for `4.x` in this direction):

1. Keep on having a `ChuckerInterceptor(Context)` constructor (i.e. our primary constructor with default values). Applying our library should as easy as that. It's reasonable to ask for a `Context` to our users as we're showing UI/Notifications, etc.
2. Have all the Android related code inside the `ChuckerCollector`. That's going to be the connection point between our library and the Android framework
3. Ideally extracting `ChuckerCollector` to an interface to better define the interaction between collector/interceptor and for better testability
4. Ideally the ChuckerInterceptor should delegate all the implementation to a pure java class that interacts with this extracted interface.

This makes code for us easier to maintain and test.

As a side note, for the sake of testing we should probably work on extracting all the `processResponseBody`, `processRequest` methods inside the `ChuckerInterceptor` to separate classes and test them in isolation. This is something we can start doing today. 
It won't fix the overall issue as you still have to mock a `ChuckerCollector` that needs a `Context`, but we can keep it as an iterative process and further improve once we extract an interface out of it.

**Comment by MiSikora** [comment]
I'm closing this. I don't deem it useful anymore.
