### ISSUE TITLE
response json body is not show when parse error

### ISSUE THREAD

**Issue by czy1121** [ChuckerTeam/chucker#425]
## :writing_hand: Describe the bug
response json body is not show

## :bomb: Steps to reproduce

```
data class SomeData(val someValue: Boolean)

interface SomeService {
    @GET("test")
    fun config(): Call<SomeData>  
}
```

if server return `{"someValue": true}`, i will see it in chucker,
if server return `{"someValue": 1}`, i can not see it in chucker, i need it

**Comment by MiSikora** [comment]
Can you please create a sample test that would show this behaviour? This one passes correctly.

```kotlin
data class SomeData(val someValue: Boolean)

interface SomeService {
    @GET("/")
    fun config(): Call<SomeData>
}

@ParameterizedTest
@EnumSource(value = ClientFactory::class)
fun test(factory: ClientFactory) {
    val body = Buffer().apply { writeUtf8("""{"someValue": 1}""") }
    server.enqueue(MockResponse().setBody(body).addHeader("Content-Type", "application/json"))

    val service = Retrofit.Builder()
            .client(factory.create(chuckerInterceptor))
            .addConverterFactory(GsonConverterFactory.create())
            .baseUrl(server.url("/"))
            .build()
            .create<SomeService>()

    val latch = CountDownLatch(1)
    service.config().enqueue(object : Callback<SomeData> {
        override fun onFailure(call: Call<SomeData>, t: Throwable) {
            latch.countDown()
        }

        override fun onResponse(call: Call<SomeData>, response: Response<SomeData>) {
            throw AssertionError()
        }
    })

    latch.await()
    val transaction = chuckerInterceptor.expectTransaction()

    assertThat(transaction.responseBody).isEqualTo("""{"someValue": 1}""")
}
```

If you use `execute` instead of `enqueue` you need to catch exceptions that your JSON converter might throw. Alternatively you should wrap your data in `Response` and use `fun config(): Call<Response<SomeData>>`.

**Comment by vbuberen** [comment]
Thanks @MiSikora for such a fast reply.

My suggestion is also about JSON converter issues there.

**Comment by czy1121** [comment]
@MiSikora 
i use Moshi 

when server return {"someValue": 1}, Moshi throw JsonDataException, it's ok

i want `{"someValue": 1}` show in chucker, but not
![Lark20200815-034041](https://user-images.githubusercontent.com/1754323/90286787-2207d780-dea9-11ea-905c-e420e3ed8984.jpeg)

**Comment by vbuberen** [comment]
@czy1121 You won't see body in Chucker if you see `JsonDataException`, because Retrofit needs some converter to parse response.

**Comment by MiSikora** [comment]
@czy1121 It doesn't matter which converter factory you use. Please create a sample or a test that can reproduce your issue. For me, it's not that obvious that even unhandled exceptions would cause this.

**Comment by vbuberen** [comment]
Hello @czy1121 

Could you provide us with some updates? 
Has anything changed for you in `3.3.0`? 

Supposedly, `alwaysReadResponseBody` is something that might work for your case.

**Comment by MiSikora** [comment]
I'm not quite sure if this was the issue because it should not happen this in the first place given the info. I'm not 100% certain if this is the case but it might be that the response body in error cases was not closed in `finally` block or with `use()` function, and that's why the content was not displayed. And nothing was displayed because since `3.2.0` we rely on response body being closed in order to update the transaction.

**Comment by czy1121** [comment]
solved, thks @MiSikora @vbuberen
