### ISSUE TITLE
Automate GH releases

### ISSUE THREAD

**Issue by MiSikora** [ChuckerTeam/chucker#484]
## :warning: Is your feature request related to a problem? Please describe

AFAIK our GH releases are done manually by @vbuberen. They could be automated by our CI.

## :bulb: Describe the solution you'd like

We could use following GH actions - [extract-release-notes](https://github.com/ffurrer2/extract-release-notes) and [action-gh-release](https://github.com/softprops/action-gh-release). I use them in another project and the setup is quite simple.

https://github.com/MiSikora/Laboratory/blob/683964d22341839e9b0c6891b391f80cf52c36e8/.github/workflows/publish-release.yaml#L38-L50

## :bar_chart: Describe alternatives you've considered

I didn't really.

## :page_facing_up: Additional context

We might want to consider which type of artifacts we want to upload to GH releases. Only compiled code or sources and javadoc as well?

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by vbuberen** [comment]
I had some more actions in notes since July as well, but never returned to them since that time.

These are https://github.com/marketplace/actions/git-release and https://github.com/release-drafter/release-drafter

In general I don't see what exactly changes for the process. We would still need to create a tag and push into the repo to launch the process on CI. The only change is that we won't have to copy contents of `CHANGELOG` to release. But it is not the issue, since I plan to abandon filling changes in releases section at all soon and leave only changelog file as a part of big docs update which I abandoned some time ago, but returned to it recently.

**Comment by MiSikora** [comment]
Oh, I didn't realise that the release section won't be filled anymore. Closing then. :)

**Comment by vbuberen** [comment]
I just didn't share the full picture of what I am trying to do, so it is fine.

Long story short: I want to have changelog only and have it on a website, hosted on Github pages.
