### ISSUE TITLE
Upgrade from 3.2.0 -> 3.3.0 creates lint errors

### ISSUE THREAD

**Issue by vtuan10** [ChuckerTeam/chucker#516]
## :writing_hand: Describe the bug

When I try to update Chucker 3.2.0 to 3.3.0, I get many Android Lint errors such as `UseAppTint` or `UseCompatLoadingForDrawables` on the actual app. 
As my Android app uses minSDK 24 these checks should not appear.

## :bomb: Steps to reproduce

1. Use app with minSDK 24
2. Add Chucker 3.3.0
3. Run `./gradlew lintDebug`

## :wrench: Expected behavior
No lint warnings

## :iphone: Tech info
 - Chucker version: 3.3.0+

**Comment by cortinico** [comment]
Thanks for your bug report.

> 2\. Add Chucker 3.3.0

- Have you tried if this is happening also with a bump to 3.4.0?
- In order to better debug can you please specify your versions of: AGP, Material Design Component (if you're using it) and AndroidX AppCompat (and related libs).

**Comment by vtuan10** [comment]
> Thanks for your bug report.
> 
> > 2. Add Chucker 3.3.0
> 
>     * Have you tried if this is happening also with a bump to 3.4.0?
> 
>     * In order to better debug can you please specify your versions of: AGP, Material Design Component (if you're using it) and AndroidX AppCompat (and related libs).

- Yes, it also happens on 3.4.0
- AGP: 4.1.1, Material Design Components: 1.1.0, AndroidX AppCompat: 1.1.0

**Comment by cortinico** [comment]
I've done some investigation and it seems like AppCompat 1.2.0 (that Chucker is using and transitively exposing) now ships with a `lint.jar` containing some extra custom lint checks.

So to answer to your problem, you can workaround this excluding the transitive dependencies on the AndroidX libraries in your build.gradle.

```
debugImplementation("com.github.chuckerteam.chucker:library:3.4.0") {
        exclude group: "androidx.appcompat", module: "appcompat"
        exclude group: "androidx.constraintlayout", module: "constraintlayout"
        exclude group: "com.google.android.material", module: "material"
}
```

As a rule of thumb, you should take care of those lint failures as they will show up as soon as you bump AndroidX AppCompat to 1.2.0.

Please verify and close if this issue is resolved.

**Comment by vtuan10** [comment]
Thanks for the help!

Adding those includes fixes the issue. We will look into updating AppCompat to 1.2.0
