### ISSUE TITLE
Recording and Replaying responses

### ISSUE THREAD

**Issue by rajab57** [ChuckerTeam/chucker#530]
## :bulb: Describe the solution you'd like
I would like to be able to record responses and replay them in tests to have consistent behavior.

## :bar_chart: Describe alternatives you've considered
I have looked at https://github.com/airbnb/okreplay but it doesnt work with latest Android plugin and not sure if it is under active development.
We are already using chucker and would be nice to have this feature extended.

## :raising_hand: Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No

**Comment by MiSikora** [comment]
Thanks for the report. I like the idea in itself. However, looking at the linked library, I don't feel that it should be a responsibility of `ChuckerInterceptor` to provide this functionallity. The inteceptor has an export functionality that can be utilized by some other tool to prepare such recorded responses.

Unfortunately, there would be some caveats due to how we always try to unzip responses and how Chucker can be applied – network vs application interceptor. Another thing to keep in mind is that we store only text and image bodies.

Still, if I like to use something like this, I wouldn't rely on this and just write a tool like `okreplay` or fix it upstream.

**Comment by vbuberen** [comment]
I don't think it is something that Chucker should do and adding such functionality will be losing focus as it was with errors tab.

**Comment by cortinico** [comment]
> I don't think it is something that Chucker should do and adding such functionality will be losing focus as it was with errors tab.

Agree. This should be an external tool. The connection point with Chucker could be, as @MiSikora mentioned, on the export tab. Specifically we could leverage a potential .har export feature #417.

Such tool could replay the saved .har, but it should not be related to Chucker or the `ChuckerInterceptor` imho.

**Comment by MiSikora** [comment]
I'll close this since we don't see that this feature fits Chucker.
