### ISSUE TITLE
Ability to pre-parse response to flag as error based on JSON in response

### ISSUE THREAD

**Issue by MKevin3** [ChuckerTeam/chucker#573]
Our server wraps errors so we get a 200 with a `"success":  false` within the returned JSON and then an error object with the error code. When I see the current Chucker list it looks like everything is perfect as it is all 200 but I would love to be able to pre-process the return to see if it really was an error and show the 200 in RED or to extract the internal code and error to have Chucker show that instead of the original unwrapped 200.

Would love some way to either flag any response as an error before it is added to the list (so it shows in RED) or even deeper processing to extract the error and text I want.

Might be too specific of an issue for team to tackle but might solve some issues for others as well.

**Comment by MiSikora** [comment]
In `4.x` we plan to add possibility to install custom body decoders. They were added in order to decode binary formats like protobuf but you can use them for your specific task as well. Right now it is available only in snapshot version but I don't expect a lot of changes (if any) to this feature.

You can write your custom decoder that removes envelopes from the payload. Here is an example that reverses received bodies.

https://github.com/ChuckerTeam/chucker/blob/186a3df44f57846d899c23e3a4f5770b683a7ef9/library/src/test/java/com/chuckerteam/chucker/api/ChuckerInterceptorDecodingTest.kt#L176-L179

**Comment by MiSikora** [comment]
Ahhh, sorry. I'm tired and misread what you wrote. You asked for color coding the responses not custom parsing. Right now it is not possible. Personally I'm not super against it but I find it too niche. Would love to hear what others think.

**Comment by cortinico** [comment]
> Personally I'm not super against it but I find it too niche

Agree, plus is complicated to develop a general solution for this feature request as it requires to check inside the encapsulated response.

How about you develop your own Interceptor that you place before Chucker that promotes the encapsulated error code to the HTTP error code?

**Comment by MKevin3** [comment]
Interesting, I am willing to give this a try. I assume we are talking a Retrofit interceptor and not a Chucker Interceptor.

**Comment by cortinico** [comment]
> Interesting, I am willing to give this a try. I assume we are talking a Retrofit interceptor and not a Chucker Interceptor.

I'm actually talking about OkHTTP interceptors:
https://square.github.io/okhttp/interceptors/

**Comment by vbuberen** [comment]
I don't find such feature useful for Chucker, since I believe that sending errors with 200 response code isn't correct.
