### ISSUE TITLE
Chucker 3.5.1: missing .aar file in maven repository

### ISSUE THREAD

**Issue by kroegerama** [ChuckerTeam/chucker#661]
I just tried to upgrade to version `3.5.1` and this release is missing the `.aar` file in mavencentral:

[library-3.5.1.aar](https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library/3.5.1/library-3.5.1.aar)

The no-op `.aar` does exist:

[library-no-op-3.5.1.aar](https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library-no-op/3.5.1/library-no-op-3.5.1.aar)

**Comment by RahulSDeshpande** [comment]
For more clarity here is the build error stack-trace:

```kt
Execution failed for task ':app:partner:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:partner:debugCompileClasspath'.
   > Could not find library-3.5.1.aar (com.github.chuckerteam.chucker:library:3.5.1).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library/3.5.1/library-3.5.1.aar

```

Please refer [maven lib artifact link](https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library/3.5.1/) for more info/proof.

**Comment by cortinico** [comment]
Thanks for reporting 👍 

As you all mentioned, it seems like that the `library-3.5.1.aar` artifact is missing. My suspect is that the CI created two staging repositories (due to Gradle parallel invocation or other concurrency) and the `.aar` artifact ended up in a separate staging repo.

I've tried to manually upload the valid artifact but seems like that sonatype is unhappy with the approach. Specifically I can't just upload a `.aar` as I need to provide also a valid signature + a valid pom. The valid signature & pom are already published on Central therefore they're read-only now, so I wasn't able to effectively craft a bundle that would allow us to upload just `library-3.5.1.aar` to central.

Is anyone in the community aware on how to fix this? As an alternative, we will probably call `3.5.1` broken and re-deploy it as `3.5.2` (version numbers are free afterall).

**Comment by kroegerama** [comment]
I think the easiest solution is to re-deploy a new version. Sonatype does not allow changing of closed+released repositories as far as i know.

**Comment by vbuberen** [comment]
Feels really strange. I will draft a `3.5.2` and let's hope this time things will work better.

**Comment by michalkierasinski** [comment]
Do you know when the new version will be available?

**Comment by vbuberen** [comment]
We plan to have it available today in some hours. I will add a new Github release after we promote build to release on Maven.

**Comment by cortinico** [comment]
Just to give some heads up on the situation. Sonatype has been slow in addressing our problems:
https://issues.sonatype.org/browse/OSSRH-71650

To unblock everyone, I believe we can manually upload the artifact produced by our CI job (this https://github.com/ChuckerTeam/chucker/actions/runs/1077874806) to sonatype directly, so Chucker `3.5.2` will be available on Maven Central.

Sadly sonatype is currently experiencing an authentication outage:
https://twitter.com/aalmiray/status/1421402353639493636
https://issues.sonatype.org/browse/OSSRH-71707
so we can't really proceed as of now.

As a temporary workaround, Chucker `3.5.2` is available on Jitpack:
https://jitpack.io/#Chuckerteam/chucker/3.5.2

**Comment by vbuberen** [comment]
`3.5.2` is already available on Maven Central, so closing this.
