### ISSUE TITLE
Hiding base url for security

### ISSUE THREAD

**Issue by kimdohun0104** [ChuckerTeam/chucker#680]
## :warning: Is your feature request related to a problem? Please describe
I'm working on Fintech startup that affiliated with many financial institutions.  
They use the stage flavor application to test our service.  
**The problem here is that the base url is exposed as it is when they approach the chucker screen.**

Although it won't open easily by customizing how to open the chucker screen.  
It's still has risk.

## :bulb: Describe the solution you'd like
In ChuckerCollector, add `collectBaseUrl` or `collectHost` like this.
```
val chuckerCollector = ChuckerCollector(
  context = this,
  collectBaseUrl = false
)
```
Then every host in Room database collect as null.

## Other idea
Just modify visibility of view if want hide base url.

## :raising_hand: Do you want to develop this feature yourself?

- [x] Yes
- [ ] No

**Comment by cortinico** [comment]
> The problem here is that the base url is exposed as it is when they approach the chucker screen.

As a side note: if you're worried about security, then you should not even distribute a Debug build or use Chucker. This library is story your requests on a Room database. This means that they will be easily accessible by everyone, regardless of the Chucker UI.

Getting back to your feature, I believe it could have some value, but I would implement it similarly to the Redact Header feature: https://github.com/ChuckerTeam/chucker#redact-header-%EF%B8%8F

However, I would like to understand better your use case. This issue is addressing the base URL, tomorrow we might have a request to redact the HTTP verb, the body or whatever. So potentially every field could be hidden due to security reasons 🤔

**Comment by kimdohun0104** [comment]
In our company, we go through the QA phase in a special way.
When an app is distributed in the Stage environment, internal and financial personnel check the same app.
The reason why I apply this library is because I want internal personnel to have access to the Chucker screen.
Financial services are not going to hack apps or do anything bad, but for some reason they are concerned that baseurl and other information will be leaked to other bad institutions.

As you said, the chucker uses the database, so even if I hide the base url, they will find it easily. (Other information, of course)
I'll discuss it with my team and think about how to provide a library-excluded app to financial institutions.
I think that's the strongest security of all.
(We can't continue to hide data based on security requirements...)

I'm so grateful to your team for improving and maintaining this wonderful library.
I think the issue should be closed.
