### ISSUE TITLE
Could not resolve okhttp when using chucker as a transitive dependency

### ISSUE THREAD

**Issue by koral--** [ChuckerTeam/chucker#687]
## :writing_hand: Describe the bug
I have a library which depends on chucker. Up to version 3.4.0 it worked fine. However, when I try to upgrade to 3.5.2 the dependency resolution fails. It seems that okhttp version from BOM is missing at this point.
I'm not sure what exactly is the source of this issue. Packaging of the chucker itself? Issue in Android Gradle Plugin?
I've just updated Chucker version and it stopped working so I'm first trying here.
My project is available here: https://github.com/DroidsOnRoids/FoQA

Issue can be worked around by manually specifying the okhttp version like chucker does:
```    
api(platform("com.squareup.okhttp3:okhttp-bom:3.12.10"))
api("com.squareup.okhttp3:okhttp")
```
I mean I can build my project but the same original issue can affect consumers of my library then.

```
Execution failed for task ':chucker_plugin:generateReleaseRFile'.
> Could not resolve all files for configuration ':chucker_plugin:releaseCompileClasspath'.
   > Could not find com.squareup.okhttp3:okhttp:.
     Required by:
         project :chucker_plugin > com.github.ChuckerTeam.Chucker:library:3.5.2

```

## :bomb: Steps to reproduce
Try to build https://github.com/DroidsOnRoids/FoQA/tree/master/chucker_plugin project with chucker 3.5.2
Set it in https://github.com/DroidsOnRoids/FoQA/blob/master/buildSrc/src/main/kotlin/Dependencies.kt#L24

## :wrench: Expected behavior
Gradle does not fail.

## :iphone: Tech info
 - Chucker version: > 3.4.0

**Comment by cortinico** [comment]
> I'm not sure what exactly is the source of this issue.

So what happens here is that, once we moved the dependency resolution to use the okhttp-bom artifact, we're not specifying an OkHTTP version explicity anymore.

It's up to the user to decide if they:
- Specify an OkHTTP version they want to depend on
- Apply the okhttp-bom artifact as well.

> I mean I can build my project but the same original issue can affect consumers of my library then.

If you specify an `implementation` dependency on `com.squareup.okhttp3:okhttp:<yourversion>` that won't happen anymore.

On a side note, I'm unsure if we want to apply a dependency on the bom also on our user or not (to make those kind of errors less frequent).

**Comment by koral--** [comment]
Could you elaborate on
> Apply the okhttp-bom artifact as well

How to do that without specifying any okhttp version?

**Comment by cortinico** [comment]
> How to do that without specifying any okhttp version?

You can't. You have to specify an OkHTTP version (either of the BOM or of the `okhttp` client).

I've done some researches on this side and it seems like that the `api(platform(...))` dependencies are not transitive (i.e. a Library developer can't force the consumer to apply a BOM).

The problem is that what we end up having in the POM is:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp-bom</artifactId>
        <version>3.12.10</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <scope>compile</scope>
    </dependency>
    ...
  </dependencies>
```

So the `com.squareup.okhttp3:okhttp` is effectively without a version.

Therefore our consumers are forced to either:
- Apply the bom as well
- Specify a version for all the dependencies from `com.squareup.okhttp3` we will ever depend on.

A couple of Gradle Slack related discussions on this are:
https://gradle-community.slack.com/archives/CAHSN3LDN/p1623924796301300
https://gradle-community.slack.com/archives/CAH4ZP3GX/p1622468998045700

I believe this is somehow a regression for our users, as they now need to specify an extra dependency. Although the impact is minimal as I expect users to already depend on OkHTTP in some form.

So far the best solution would be to move over to Version catalog or some other version management and avoid depending on the bom.

**Comment by koral--** [comment]
Thanks for the explanation. I'm closing this ticket since it is not an issue with Chucker itself.
