### ISSUE TITLE
Problem with adding dependency in remote repository

### ISSUE THREAD

**Issue by anatoliyRodkin** [ChuckerTeam/chucker#876]
The situation is the following. I have my project and a separate repository, which contains all the code responsible for the network, requests, and more. I added the dependencies and interceptor to this remote repository and added the dependency of this repository to my project. Chuker in this case does not display anything and does not seem to work at all. Are there any solutions for this?

**Comment by vbuberen** [comment]
There is not enough info about the issue. We have bug report template for a reason.

**Comment by anatoliyRodkin** [comment]
> There is not enough info about the issue. We have bug report template for a reason.

I'm not sure if this is a bug. It also does not fit the definition of new feature. So I just wanted to get some help from you.

**Comment by vbuberen** [comment]
Without detailed explanation about project setup, Chucker version, what you did and what is `does not seem to work at all` in your mind it is impossible to help. If something is obvious to you because you work with this project it doesn't mean that a stranger from the internet should now what goes on in your project, etc.

**Comment by cortinico** [comment]
> So I just wanted to get some help from you.

Please provide a reproducer of some sort otherwise is really hard to understand what is your problem and how we can support you 👍
